version: '3'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - redis
    networks:
      - fastapi-network

  redis:
    image: "redis:alpine"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
